# MySQL8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/saessak?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  # SQL
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

kakao:
  client:
    id: 8a0f1735f002f9571ca3a2c4e30db8da
    secret: wR3nvxNdDN0AMMBjsiznkFMGewPSwSql
  redirect:
    url: http://localhost:8080/api/oauth/kakao/callback

jwt:
  token:
    secret-key: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa
  access-token:
    expire-length: 1800000
  refresh-token:
    expire-length: 1209600000

cloud:
  aws:
    s3:
      bucket: saessack-photo-album
    credentials:
      access-key: AKIAUZRXT2PHNBJ4QE7T
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false