# MySQL8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/saessak?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  # SQL
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

kakao:
  client:
    id: 8a0f1735f002f9571ca3a2c4e30db8da
    secret: wR3nvxNdDN0AMMBjsiznkFMGewPSwSql
  redirect:
    url: http://localhost:8080/oauth/kakao/callback

#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: 8a0f1735f002f9571ca3a2c4e30db8da
#            redirect-uri: http://localhost:3000/oauth/kakao
#            client-authentication-method: POST
#            client-secret: wR3nvxNdDN0AMMBjsiznkFMGewPSwSql
#            authorization-grant-type: authorization_code
#            scope:
#              - profile_nickname
#              - profile_image
#              - account_email
#              - gender
#              - birthday
#            client_name: kakao
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id

jwt:
  token:
    secret-key: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa
  access-token:
    expire-length: 1800000
  refresh-token:
    expire-length: 1209600000